### ISSUE TITLE
Goal reset? 

### ISSUE THREAD

**Issue by jmbruel** [CodyJung/connectiq-apps#5]
Each time I set a new goal the entered number just adds to the previous number! Can't find how to reset the goal.

**Comment by CodyJung** [comment]
Ach, sorry - I apparently don't get emails for new issues.
I'm not seeing that happen on my watch. What version of Fenix 3 (or D2 Bravo) software do you have?

**Comment by CodyJung** [comment]
I'm going to close this as Can't Reproduce. Also try taking a look at version 1.1.0 - I changed how the number picker works, and hopefully that'll fix your issue?
